# -*- coding: utf-8 -*-
"""USA_Housing CSV Streamlit- Erica Nie

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c8mAYHzSKVtDkfER7B7GUN37WsbTWvpK
"""

!curl ipecho.net/plain

!pip install streamlit --quiet
!pip install pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import seaborn as sns
# 
# st.write("Presentation on USA Housing Dataset")
# st.title("Analysis on USA Housing")
# 
# df_housing=pd.read_csv("USA_Housing.csv")
# st.dataframe(df_housing)
# df_housing.head(5)
# 
# st.line_chart(data = df_housing, x="Avg. Area Number of Bedrooms", y="Area Population")

!streamlit run app.py & npx localtunnel --port 8501

!pip freeze > requirements.txt